import PDFDocument from "pdfkit";

import { pool } from "../db/pool.js";

const VALID_PERIODS = ["day", "week", "month"];
const VALID_GUARD_PERIODS = ["today", "day", "week", "month"];
const VALID_REPORT_TYPES = ["dashboard_summary", "parcel_records", "user_account_summary"];
const VALID_REPORT_FORMATS = ["csv", "pdf"];

function toIso(value) {
  return value instanceof Date ? value.toISOString() : new Date(value).toISOString();
}

function startOfDay(date) {
  const result = new Date(date);
  result.setHours(0, 0, 0, 0);
  return result;
}

function startOfMonth(date) {
  return new Date(date.getFullYear(), date.getMonth(), 1);
}

function addDays(date, days) {
  const result = new Date(date);
  result.setDate(result.getDate() + days);
  return result;
}

function addMonths(date, months) {
  return new Date(date.getFullYear(), date.getMonth() + months, 1);
}

function addCalendarMonths(date, months) {
  const day = date.getDate();
  const result = new Date(date.getFullYear(), date.getMonth() + months, 1);
  const lastDay = new Date(result.getFullYear(), result.getMonth() + 1, 0).getDate();
  result.setDate(Math.min(day, lastDay));
  result.setHours(date.getHours(), date.getMinutes(), date.getSeconds(), date.getMilliseconds());
  return result;
}

function parseDateInput(value) {
  if (!value) {
    return null;
  }

  if (!/^\d{4}-\d{2}-\d{2}$/.test(value)) {
    return null;
  }

  const [year, month, day] = value.split("-").map(Number);
  const date = new Date(year, month - 1, day);

  if (
    date.getFullYear() !== year ||
    date.getMonth() !== month - 1 ||
    date.getDate() !== day
  ) {
    return null;
  }

  date.setHours(0, 0, 0, 0);
  return date;
}

function calculateChangePercent(currentValue, comparisonValue) {
  if (comparisonValue === null || comparisonValue === undefined) {
    return null;
  }

  if (comparisonValue === 0) {
    return currentValue === 0 ? 0 : null;
  }

  return Number((((currentValue - comparisonValue) / comparisonValue) * 100).toFixed(2));
}

function numberValue(value) {
  return Number(value || 0);
}

function titleCaseReportType(value) {
  return String(value)
    .split("_")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ");
}

function reportSlug(value) {
  return String(value || "")
    .replace(/_/g, "-")
    .replace(/[^a-z0-9-]/gi, "")
    .toLowerCase();
}

function displayUserName(user) {
  const name = `${user?.first_name || ""} ${user?.last_name || ""}`.trim();

  if (name) {
    return name;
  }

  return user?.email || "Admin";
}

function formatDateTime(value) {
  if (!value) {
    return "";
  }

  const date = value instanceof Date ? value : new Date(value);

  if (Number.isNaN(date.getTime())) {
    return "";
  }

  return date.toISOString();
}

function csvEscape(value) {
  if (value === null || value === undefined) {
    return "";
  }

  const text = String(value);

  if (/[",\n\r]/.test(text)) {
    return `"${text.replace(/"/g, '""')}"`;
  }

  return text;
}

function csvRow(values) {
  return values.map(csvEscape).join(",");
}

function csvSection(title, rows = []) {
  return [title, ...rows.map(csvRow), ""].join("\n");
}

function createMetadata({ reportType, format, config, requester, startDate }) {
  return {
    reportTitle: `Parcel Nexus ${titleCaseReportType(reportType)} Report`,
    reportType,
    format,
    generatedAt: new Date().toISOString(),
    generatedBy: displayUserName(requester),
    generatedByEmail: requester?.email || "",
    period: config.period,
    rangeStart: toIso(config.start),
    rangeEnd: toIso(config.end),
    systemName: "Parcel Nexus",
    property: "GEM Condominium",
    requestedStartDate: startDate || ""
  };
}

function metadataRows(metadata) {
  return [
    ["Field", "Value"],
    ["Report Title", metadata.reportTitle],
    ["Report Type", metadata.reportType],
    ["Format", metadata.format],
    ["Generated At", metadata.generatedAt],
    ["Generated By", metadata.generatedBy],
    ["Generated By Email", metadata.generatedByEmail],
    ["Period", metadata.period],
    ["Range Start", metadata.rangeStart],
    ["Range End", metadata.rangeEnd],
    ["System Name", metadata.systemName],
    ["Property", metadata.property]
  ];
}

function getPeriodConfig(period, { startDate } = {}) {
  const now = new Date();
  const selectedStart = startDate ? parseDateInput(startDate) : null;

  if (startDate && !selectedStart) {
    return { error: "INVALID_START_DATE" };
  }

  if (selectedStart) {
    if (period === "week") {
      return {
        period,
        label: "Selected 7 days",
        start: selectedStart,
        end: addDays(selectedStart, 7),
        previousStart: addDays(selectedStart, -7),
        previousEnd: selectedStart,
        comparisonLabel: "vs previous 7 days",
        trendStep: "1 day",
        trendFormat: "Dy, DD Mon"
      };
    }

    if (period === "month") {
      const end = addCalendarMonths(selectedStart, 1);
      return {
        period,
        label: "Selected month range",
        start: selectedStart,
        end,
        previousStart: addCalendarMonths(selectedStart, -1),
        previousEnd: selectedStart,
        comparisonLabel: "vs previous month",
        trendStep: "1 day",
        trendFormat: "DD Mon"
      };
    }

    return {
      period: "day",
      label: "Selected day",
      start: selectedStart,
      end: addDays(selectedStart, 1),
      previousStart: addDays(selectedStart, -1),
      previousEnd: selectedStart,
      comparisonLabel: "vs previous day",
      trendStep: "1 hour",
      trendFormat: "HH24:00"
    };
  }

  if (period === "week") {
    const start = addDays(now, -6);
    start.setHours(0, 0, 0, 0);
    const previousStart = addDays(start, -7);
    const previousEnd = start;

    return {
      period,
      label: "Last 7 days",
      start,
      end: now,
      previousStart,
      previousEnd,
      comparisonLabel: "vs previous 7 days",
      trendStep: "1 day",
      trendFormat: "Dy, DD Mon"
    };
  }

  if (period === "month") {
    const start = startOfMonth(now);
    const previousStart = addMonths(start, -1);
    const previousEnd = start;

    return {
      period,
      label: "This month",
      start,
      end: now,
      previousStart,
      previousEnd,
      comparisonLabel: "vs previous month",
      trendStep: "1 day",
      trendFormat: "DD Mon"
    };
  }

  const start = startOfDay(now);
  const previousStart = addDays(start, -1);

  return {
    period: "day",
    label: "Today",
    start,
    end: now,
    previousStart,
    previousEnd: start,
    comparisonLabel: "vs yesterday",
    trendStep: "1 hour",
    trendFormat: "HH24:00"
  };
}

function getGuardPeriodConfig(period = "today", { startDate } = {}) {
  const normalizedPeriod = period === "day" ? "today" : period;

  if (!VALID_GUARD_PERIODS.includes(period)) {
    return { error: "INVALID_GUARD_PERIOD" };
  }

  const selectedStart = startDate ? parseDateInput(startDate) : startOfDay(new Date());

  if (startDate && !selectedStart) {
    return { error: "INVALID_START_DATE" };
  }

  if (normalizedPeriod === "week") {
    return {
      period: "week",
      selected: "week",
      label: "Selected 7 days",
      start: selectedStart,
      end: addDays(selectedStart, 7)
    };
  }

  if (normalizedPeriod === "month") {
    return {
      period: "month",
      selected: "month",
      label: "Selected month range",
      start: selectedStart,
      end: addCalendarMonths(selectedStart, 1)
    };
  }

  return {
    period: "day",
    selected: "today",
    label: "Selected day",
    start: selectedStart,
    end: addDays(selectedStart, 1)
  };
}

async function getRangeParcelCount({ start, end }) {
  const result = await pool.query(
    `
      SELECT COUNT(*)::int AS count
      FROM parcels
      WHERE deleted_at IS NULL
        AND created_at >= $1
        AND created_at < $2
    `,
    [start, end]
  );

  return numberValue(result.rows[0]?.count);
}

async function getRangeCollectedCount({ start, end }) {
  const result = await pool.query(
    `
      SELECT COUNT(*)::int AS count
      FROM parcels
      WHERE deleted_at IS NULL
        AND status = 'COLLECTED'
        AND COALESCE(collected_at, updated_at) >= $1
        AND COALESCE(collected_at, updated_at) < $2
    `,
    [start, end]
  );

  return numberValue(result.rows[0]?.count);
}

async function getCurrentPendingAndOverdue() {
  const result = await pool.query(
    `
      SELECT
        COUNT(*) FILTER (
          WHERE status IN ('PENDING', 'PENDING_COLLECTION')
        )::int AS pending_collection,
        COUNT(*) FILTER (
          WHERE status IN ('PENDING', 'PENDING_COLLECTION')
            AND collection_deadline IS NOT NULL
            AND collection_deadline < NOW()
        )::int AS overdue_count
      FROM parcels
      WHERE deleted_at IS NULL
    `
  );

  return {
    pendingCollection: numberValue(result.rows[0]?.pending_collection),
    overdueCount: numberValue(result.rows[0]?.overdue_count)
  };
}

async function tableExists(tableName) {
  const result = await pool.query("SELECT to_regclass($1) AS table_name", [`public.${tableName}`]);
  return Boolean(result.rows[0]?.table_name);
}

async function getDisputeKpi({ start, end, previousStart, previousEnd, comparisonLabel }) {
  const disputesAvailable = await tableExists("disputes");

  if (!disputesAvailable) {
    return {
      kpi: {
        label: "Open Disputes",
        available: false,
        value: 0,
        new_count: 0,
        message: "Dispute module is not implemented yet."
      },
      summary: {
        available: false,
        items: [],
        message: "Dispute module is not implemented yet."
      }
    };
  }

  const result = await pool.query(
    `
      SELECT
        COUNT(*) FILTER (WHERE status IN ('OPEN', 'IN_REVIEW', 'ESCALATED'))::int AS open_disputes,
        COUNT(*) FILTER (WHERE created_at >= $1 AND created_at < $2)::int AS new_count,
        COUNT(*) FILTER (WHERE created_at >= $3 AND created_at < $4)::int AS previous_new_count,
        COUNT(*) FILTER (WHERE status = 'OPEN')::int AS open_count,
        COUNT(*) FILTER (WHERE status = 'IN_REVIEW')::int AS in_review_count,
        COUNT(*) FILTER (WHERE status = 'ESCALATED')::int AS escalated_count,
        COUNT(*) FILTER (WHERE status = 'RESOLVED')::int AS resolved_count
      FROM disputes
    `,
    [start, end, previousStart, previousEnd]
  );
  const row = result.rows[0] || {};
  const newCount = numberValue(row.new_count);
  const previousNewCount = numberValue(row.previous_new_count);

  return {
    kpi: {
      label: "Open Disputes",
      available: true,
      value: numberValue(row.open_disputes),
      new_count: newCount,
      comparison_label: comparisonLabel,
      comparison_value: previousNewCount,
      change_percent: calculateChangePercent(newCount, previousNewCount)
    },
    summary: {
      available: true,
      items: [
        { status: "Open", count: numberValue(row.open_count) },
        { status: "In Review", count: numberValue(row.in_review_count) },
        { status: "Escalated", count: numberValue(row.escalated_count) },
        { status: "Resolved", count: numberValue(row.resolved_count) }
      ],
      message: ""
    }
  };
}

async function getParcelTrend(config) {
  const result = await pool.query(
    `
      WITH buckets AS (
        SELECT generate_series(
          $1::timestamptz,
          $2::timestamptz,
          $3::interval
        ) AS bucket_start
      )
      SELECT
        b.bucket_start,
        LEAST(b.bucket_start + $3::interval, $2::timestamptz) AS bucket_end,
        to_char(b.bucket_start, $4) AS label,
        COUNT(DISTINCT received.parcel_id)::int AS parcels_received,
        COUNT(DISTINCT collected.parcel_id)::int AS collected_same_day
      FROM buckets b
      LEFT JOIN parcels received
        ON received.deleted_at IS NULL
       AND received.created_at >= b.bucket_start
       AND received.created_at < LEAST(b.bucket_start + $3::interval, $2::timestamptz)
      LEFT JOIN parcels collected
        ON collected.deleted_at IS NULL
       AND collected.status = 'COLLECTED'
       AND COALESCE(collected.collected_at, collected.updated_at) >= b.bucket_start
       AND COALESCE(collected.collected_at, collected.updated_at) < LEAST(b.bucket_start + $3::interval, $2::timestamptz)
      WHERE b.bucket_start < $2::timestamptz
      GROUP BY b.bucket_start
      ORDER BY b.bucket_start
    `,
    [config.start, config.end, config.trendStep, config.trendFormat]
  );

  return result.rows.map((row) => ({
    label: row.label,
    bucket_start: row.bucket_start,
    bucket_end: row.bucket_end,
    parcels_received: numberValue(row.parcels_received),
    collected_same_day: numberValue(row.collected_same_day)
  }));
}

async function getStatusDistribution() {
  const result = await pool.query(
    `
      SELECT
        COUNT(*) FILTER (
          WHERE status IN ('PENDING', 'PENDING_COLLECTION')
            AND (
              collection_deadline IS NULL
              OR collection_deadline >= NOW()
            )
        )::int AS pending_collection,
        COUNT(*) FILTER (
          WHERE status IN ('PENDING', 'PENDING_COLLECTION')
            AND collection_deadline IS NOT NULL
            AND collection_deadline < NOW()
        )::int AS overdue,
        COUNT(*) FILTER (
          WHERE status = 'COLLECTED'
        )::int AS collected
      FROM parcels
      WHERE deleted_at IS NULL
    `
  );
  const pendingCollection = numberValue(result.rows[0]?.pending_collection);
  const overdue = numberValue(result.rows[0]?.overdue);
  const collected = numberValue(result.rows[0]?.collected);
  const total = pendingCollection + overdue + collected;

  function percentage(count) {
    return total === 0 ? 0 : Number(((count / total) * 100).toFixed(2));
  }

  return [
    {
      status: "Pending Collection",
      count: pendingCollection,
      percentage: percentage(pendingCollection)
    },
    {
      status: "Overdue",
      count: overdue,
      percentage: percentage(overdue)
    },
    {
      status: "Collected",
      count: collected,
      percentage: percentage(collected)
    }
  ];
}

async function getSystemSummary() {
  const result = await pool.query(
    `
      SELECT
        (SELECT COUNT(*)::int FROM users WHERE status = 'ACTIVE') AS active_users,
        (SELECT COUNT(*)::int FROM users WHERE role = 'GUARD') AS guards,
        (SELECT COUNT(*)::int FROM users WHERE role = 'RESIDENT') AS residents,
        (SELECT COUNT(*)::int FROM units) AS units,
        (SELECT COUNT(DISTINCT block)::int FROM units WHERE block IS NOT NULL AND block <> '') AS towers
    `
  );
  const row = result.rows[0] || {};

  return {
    active_users: numberValue(row.active_users),
    guards: numberValue(row.guards),
    residents: numberValue(row.residents),
    units: numberValue(row.units),
    towers: numberValue(row.towers)
  };
}

async function getRecentActivity() {
  const result = await pool.query(
    `
      (
        SELECT
          'parcel_logged' AS type,
          'Parcel logged' AS title,
          CONCAT(u.full_unit_code, ' · ', c.courier_name) AS description,
          CASE
            WHEN p.status = 'COLLECTED' THEN 'Collected'
            WHEN p.status IN ('PENDING', 'PENDING_COLLECTION')
              AND p.collection_deadline IS NOT NULL
              AND p.collection_deadline < NOW()
              THEN 'Overdue'
            ELSE 'Pending Collection'
          END AS status,
          p.created_at
        FROM parcels p
        INNER JOIN units u ON u.unit_id = p.unit_id
        INNER JOIN courier_companies c ON c.courier_id = p.courier_id
        WHERE p.deleted_at IS NULL
      )
      UNION ALL
      (
        SELECT
          'account_created' AS type,
          'Account created' AS title,
          CONCAT(COALESCE(NULLIF(TRIM(CONCAT(first_name, ' ', last_name)), ''), email), ' · ', role) AS description,
          status,
          created_at
        FROM users
        WHERE role IN ('ADMIN', 'GUARD', 'RESIDENT')
      )
      ORDER BY created_at DESC
      LIMIT 8
    `
  );

  return result.rows.map((row) => ({
    type: row.type,
    title: row.title,
    description: row.description,
    status: row.status,
    created_at: row.created_at
  }));
}

function getParcelDisplayStatus(row) {
  if (row.status === "COLLECTED") {
    return "Collected";
  }

  if (row.is_overdue) {
    return "Overdue";
  }

  return "Pending Collection";
}

function mapGuardParcelRow(row) {
  return {
    parcel_id: row.parcel_id,
    tracking_number: row.tracking_number,
    unit_full_code: row.unit_full_code,
    courier_name: row.courier_name,
    courier_code: row.courier_code,
    display_status: getParcelDisplayStatus(row),
    is_overdue: Boolean(row.is_overdue),
    collection_deadline: row.collection_deadline,
    created_at: row.created_at
  };
}

async function getGuardSummary({ start, end }) {
  const result = await pool.query(
    `
      SELECT
        COUNT(*) FILTER (
          WHERE created_at >= $1
            AND created_at < $2
        )::int AS parcels_logged,
        COUNT(*) FILTER (
          WHERE status IN ('PENDING', 'PENDING_COLLECTION')
        )::int AS pending_collection,
        COUNT(*) FILTER (
          WHERE status = 'COLLECTED'
            AND COALESCE(collected_at, updated_at) >= $1
            AND COALESCE(collected_at, updated_at) < $2
        )::int AS collected_parcels,
        COUNT(*) FILTER (
          WHERE status IN ('PENDING', 'PENDING_COLLECTION')
            AND collection_deadline IS NOT NULL
            AND collection_deadline < NOW()
        )::int AS overdue_parcels
      FROM parcels
      WHERE deleted_at IS NULL
    `,
    [start, end]
  );
  const row = result.rows[0] || {};

  return {
    parcels_logged: numberValue(row.parcels_logged),
    pending_collection: numberValue(row.pending_collection),
    collected_parcels: numberValue(row.collected_parcels),
    overdue_parcels: numberValue(row.overdue_parcels)
  };
}

async function getLatestLoggedParcelsForGuard() {
  const result = await pool.query(
    `
      SELECT
        p.parcel_id,
        p.tracking_number,
        p.status,
        (
          p.status IN ('PENDING', 'PENDING_COLLECTION')
          AND p.collection_deadline IS NOT NULL
          AND p.collection_deadline < NOW()
        ) AS is_overdue,
        u.full_unit_code AS unit_full_code,
        c.courier_name,
        c.courier_code,
        p.collection_deadline,
        p.created_at
      FROM parcels p
      LEFT JOIN units u ON u.unit_id = p.unit_id
      LEFT JOIN courier_companies c ON c.courier_id = p.courier_id
      WHERE p.deleted_at IS NULL
      ORDER BY p.created_at DESC
      LIMIT 5
    `
  );

  return result.rows.map(mapGuardParcelRow);
}

async function getPendingCollectionParcelsForGuard() {
  const result = await pool.query(
    `
      SELECT
        p.parcel_id,
        p.tracking_number,
        p.status,
        (
          p.status IN ('PENDING', 'PENDING_COLLECTION')
          AND p.collection_deadline IS NOT NULL
          AND p.collection_deadline < NOW()
        ) AS is_overdue,
        u.full_unit_code AS unit_full_code,
        c.courier_name,
        c.courier_code,
        p.collection_deadline,
        p.created_at
      FROM parcels p
      LEFT JOIN units u ON u.unit_id = p.unit_id
      LEFT JOIN courier_companies c ON c.courier_id = p.courier_id
      WHERE p.deleted_at IS NULL
        AND p.status IN ('PENDING', 'PENDING_COLLECTION')
      ORDER BY
        CASE
          WHEN p.collection_deadline IS NOT NULL AND p.collection_deadline < NOW() THEN 0
          ELSE 1
        END,
        p.collection_deadline ASC NULLS LAST,
        p.created_at DESC
      LIMIT 5
    `
  );

  return result.rows.map(mapGuardParcelRow);
}

async function getParcelRecordsForReport(config) {
  const result = await pool.query(
    `
      SELECT
        p.tracking_number,
        p.status,
        CASE
          WHEN p.status = 'COLLECTED' THEN 'Collected'
          WHEN p.status IN ('PENDING', 'PENDING_COLLECTION')
            AND p.collection_deadline IS NOT NULL
            AND p.collection_deadline < NOW()
            THEN 'Overdue'
          ELSE 'Pending Collection'
        END AS display_status,
        (
          p.status IN ('PENDING', 'PENDING_COLLECTION')
          AND p.collection_deadline IS NOT NULL
          AND p.collection_deadline < NOW()
        ) AS is_overdue,
        u.full_unit_code AS unit_full_code,
        c.courier_name,
        c.courier_code,
        COALESCE(NULLIF(TRIM(CONCAT(registered.first_name, ' ', registered.last_name)), ''), registered.email) AS registered_by_name,
        registered.email AS registered_by_email,
        p.delivery_person_contact,
        p.parcel_photo_url,
        p.collection_deadline,
        p.created_at,
        p.updated_at
      FROM parcels p
      LEFT JOIN units u ON u.unit_id = p.unit_id
      LEFT JOIN courier_companies c ON c.courier_id = p.courier_id
      LEFT JOIN users registered ON registered.user_id = p.registered_by
      WHERE p.deleted_at IS NULL
        AND p.created_at >= $1
        AND p.created_at < $2
      ORDER BY p.created_at DESC
    `,
    [config.start, config.end]
  );

  return result.rows.map((row) => ({
    tracking_number: row.tracking_number,
    status: row.status,
    display_status: row.display_status,
    is_overdue: Boolean(row.is_overdue),
    unit_full_code: row.unit_full_code,
    courier_name: row.courier_name,
    courier_code: row.courier_code,
    registered_by_name: row.registered_by_name,
    registered_by_email: row.registered_by_email,
    delivery_person_contact: row.delivery_person_contact,
    parcel_photo_url: row.parcel_photo_url,
    collection_deadline: formatDateTime(row.collection_deadline),
    created_at: formatDateTime(row.created_at),
    updated_at: formatDateTime(row.updated_at)
  }));
}

async function getUserAccountSummaryForReport(config) {
  const [summaryResult, trendResult] = await Promise.all([
    pool.query(
      `
        SELECT role, status, COUNT(*)::int AS total_count
        FROM users
        WHERE role IN ('SUPER_ADMIN', 'ADMIN', 'GUARD', 'RESIDENT')
        GROUP BY role, status
        ORDER BY role, status
      `
    ),
    pool.query(
      `
        SELECT to_char(date_trunc('month', created_at), 'YYYY-MM') AS account_creation_month,
               COUNT(*)::int AS new_account_count
        FROM users
        WHERE role IN ('ADMIN', 'GUARD', 'RESIDENT')
          AND created_at >= $1
          AND created_at < $2
        GROUP BY date_trunc('month', created_at)
        ORDER BY date_trunc('month', created_at)
      `,
      [config.start, config.end]
    )
  ]);

  return {
    roleStatusSummary: summaryResult.rows.map((row) => ({
      role: row.role,
      status: row.status,
      total_count: numberValue(row.total_count)
    })),
    accountCreationTrend: trendResult.rows.map((row) => ({
      account_creation_month: row.account_creation_month,
      new_account_count: numberValue(row.new_account_count)
    }))
  };
}

function buildDashboardSummaryCsv({ metadata, dashboard }) {
  const kpis = dashboard.kpis || {};
  const sections = [
    csvSection("Report Metadata", metadataRows(metadata)),
    csvSection("KPI Summary", [
      ["Metric", "Value"],
      ["Parcels Logged", numberValue(kpis.total_parcels?.value)],
      ["Pending Collection", numberValue(kpis.pending_collection?.value)],
      ["Collected Parcels", numberValue(kpis.collected?.value)],
      ["Overdue Parcels", numberValue(kpis.pending_collection?.overdue_count)],
      ["Open Disputes", numberValue(kpis.open_disputes?.value)],
      ["Dispute Data Available", kpis.open_disputes?.available === false ? "No" : "Yes"]
    ]),
    csvSection("Parcel Activity Trend", [
      ["Label", "Parcels Received", "Collected Same Day"],
      ...(dashboard.parcel_trend || []).map((item) => [
        item.label,
        numberValue(item.parcels_received),
        numberValue(item.collected_same_day)
      ])
    ]),
    csvSection("Parcel Status Distribution", [
      ["Status", "Count", "Percentage"],
      ...(dashboard.status_distribution || []).map((item) => [
        item.status,
        numberValue(item.count),
        numberValue(item.percentage)
      ])
    ]),
    csvSection("System Summary", [
      ["Metric", "Value"],
      ["Active Users", numberValue(dashboard.system_summary?.active_users)],
      ["Guards", numberValue(dashboard.system_summary?.guards)],
      ["Residents", numberValue(dashboard.system_summary?.residents)],
      ["Units", numberValue(dashboard.system_summary?.units)],
      ["Towers", numberValue(dashboard.system_summary?.towers)]
    ]),
    csvSection("Dispute Summary", dashboard.dispute_summary?.available
      ? [
          ["Status", "Count"],
          ...dashboard.dispute_summary.items.map((item) => [item.status, numberValue(item.count)])
        ]
      : [
          ["Message"],
          [dashboard.dispute_summary?.message || "Dispute module is not implemented yet."]
        ]),
    csvSection("Recent Activity", [
      ["Type", "Title", "Description", "Status", "Created At"],
      ...(dashboard.recent_activity || []).map((item) => [
        item.type,
        item.title,
        item.description,
        item.status,
        formatDateTime(item.created_at)
      ])
    ])
  ];

  return `${sections.join("\n")}\n`;
}

function buildParcelRecordsCsv({ metadata, records }) {
  return `${csvSection("Report Metadata", metadataRows(metadata))}\n${csvSection("Parcel Records", [
    [
      "Tracking Number",
      "Status",
      "Display Status",
      "Is Overdue",
      "Unit Full Code",
      "Courier Name",
      "Courier Code",
      "Registered By Name",
      "Registered By Email",
      "Delivery Person Contact",
      "Parcel Photo URL",
      "Collection Deadline",
      "Created At",
      "Updated At"
    ],
    ...records.map((record) => [
      record.tracking_number,
      record.status,
      record.display_status,
      record.is_overdue ? "Yes" : "No",
      record.unit_full_code,
      record.courier_name,
      record.courier_code,
      record.registered_by_name,
      record.registered_by_email,
      record.delivery_person_contact,
      record.parcel_photo_url,
      record.collection_deadline,
      record.created_at,
      record.updated_at
    ])
  ])}\n`;
}

function buildUserAccountSummaryCsv({ metadata, summary }) {
  return `${csvSection("Report Metadata", metadataRows(metadata))}\n${csvSection("Role And Status Summary", [
    ["Role", "Status", "Total Count"],
    ...summary.roleStatusSummary.map((item) => [item.role, item.status, item.total_count])
  ])}\n${csvSection("Account Creation Trend", [
    ["Account Creation Month", "New Account Count"],
    ...summary.accountCreationTrend.map((item) => [
      item.account_creation_month,
      item.new_account_count
    ])
  ])}\n`;
}

function addPdfHeader(doc, metadata) {
  doc.fontSize(18).fillColor("#0b2239").text(metadata.reportTitle);
  doc.moveDown(0.2);
  doc.fontSize(11).fillColor("#4f5b67").text("GEM Condominium");
  doc.moveDown(0.8);
  doc.fontSize(9).fillColor("#4f5b67");
  doc.text(`Generated at: ${metadata.generatedAt}`);
  doc.text(`Generated by: ${metadata.generatedBy}${metadata.generatedByEmail ? ` (${metadata.generatedByEmail})` : ""}`);
  doc.text(`Period: ${metadata.period}`);
  doc.text(`Range: ${metadata.rangeStart} to ${metadata.rangeEnd}`);
  doc.moveDown(1);
}

function ensurePdfSpace(doc, height = 90) {
  if (doc.y + height > doc.page.height - doc.page.margins.bottom) {
    doc.addPage();
  }
}

function addPdfSectionTitle(doc, title) {
  ensurePdfSpace(doc, 45);
  doc.moveDown(0.5);
  doc.fontSize(13).fillColor("#0b2239").text(title);
  doc.moveDown(0.25);
}

function addPdfRows(doc, headers, rows) {
  const line = (values, isHeader = false) => {
    ensurePdfSpace(doc, 28);
    doc
      .fontSize(isHeader ? 8 : 8)
      .fillColor(isHeader ? "#0b2239" : "#2c3742")
      .font(isHeader ? "Helvetica-Bold" : "Helvetica")
      .text(values.map((value) => String(value ?? "")).join("   |   "), {
        width: doc.page.width - doc.page.margins.left - doc.page.margins.right
      });
    doc.moveDown(0.35);
  };

  line(headers, true);
  rows.forEach((row) => line(row));
  doc.font("Helvetica");
}

function addPdfBars(doc, rows, labelKey, valueKey) {
  const maxValue = Math.max(1, ...rows.map((row) => numberValue(row[valueKey])));

  rows.forEach((row) => {
    ensurePdfSpace(doc, 28);
    const value = numberValue(row[valueKey]);
    const barWidth = Math.round((value / maxValue) * 180);
    const y = doc.y + 3;
    doc.fontSize(8).fillColor("#2c3742").text(`${row[labelKey]} (${value})`, doc.x, doc.y, { width: 170 });
    doc.rect(doc.x + 180, y, 180, 8).fill("#edf0f2");
    doc.rect(doc.x + 180, y, barWidth, 8).fill("#0b2239");
    doc.moveDown(0.7);
  });
}

function buildPdfBuffer(render) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 42, size: "A4", bufferPages: true });
    const chunks = [];

    doc.on("data", (chunk) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    render(doc);
    const pageCount = doc.bufferedPageRange().count;

    for (let index = 0; index < pageCount; index += 1) {
      doc.switchToPage(index);
      doc
        .fontSize(8)
        .fillColor("#88919b")
        .text(`Parcel Nexus · Page ${index + 1} of ${pageCount}`, 42, doc.page.height - 34, {
          align: "center"
        });
    }

    doc.end();
  });
}

function buildDashboardSummaryPdf({ metadata, dashboard }) {
  return buildPdfBuffer((doc) => {
    addPdfHeader(doc, metadata);
    const kpis = dashboard.kpis || {};

    addPdfSectionTitle(doc, "KPI Summary");
    addPdfRows(doc, ["Metric", "Value"], [
      ["Parcels Logged", numberValue(kpis.total_parcels?.value)],
      ["Pending Collection", numberValue(kpis.pending_collection?.value)],
      ["Collected Parcels", numberValue(kpis.collected?.value)],
      ["Overdue Parcels", numberValue(kpis.pending_collection?.overdue_count)],
      ["Open Disputes", numberValue(kpis.open_disputes?.value)]
    ]);

    addPdfSectionTitle(doc, "Parcel Activity Trend");
    addPdfRows(doc, ["Label", "Parcels Received", "Collected Same Day"], (dashboard.parcel_trend || []).map((item) => [
      item.label,
      numberValue(item.parcels_received),
      numberValue(item.collected_same_day)
    ]));

    addPdfSectionTitle(doc, "Parcel Status Distribution");
    addPdfRows(doc, ["Status", "Count", "Percentage"], (dashboard.status_distribution || []).map((item) => [
      item.status,
      numberValue(item.count),
      `${numberValue(item.percentage)}%`
    ]));
    addPdfBars(doc, dashboard.status_distribution || [], "status", "count");

    addPdfSectionTitle(doc, "System Summary");
    addPdfRows(doc, ["Metric", "Value"], [
      ["Active Users", numberValue(dashboard.system_summary?.active_users)],
      ["Guards", numberValue(dashboard.system_summary?.guards)],
      ["Residents", numberValue(dashboard.system_summary?.residents)],
      ["Units", numberValue(dashboard.system_summary?.units)],
      ["Towers", numberValue(dashboard.system_summary?.towers)]
    ]);

    addPdfSectionTitle(doc, "Dispute Summary");
    if (dashboard.dispute_summary?.available) {
      addPdfRows(doc, ["Status", "Count"], dashboard.dispute_summary.items.map((item) => [
        item.status,
        numberValue(item.count)
      ]));
    } else {
      doc.fontSize(9).fillColor("#4f5b67").text(dashboard.dispute_summary?.message || "Dispute module is not implemented yet.");
    }

    addPdfSectionTitle(doc, "Recent Activity");
    const activityRows = (dashboard.recent_activity || []).map((item) => [
      item.type,
      item.title,
      item.description,
      item.status || "",
      formatDateTime(item.created_at)
    ]);
    addPdfRows(doc, ["Type", "Title", "Description", "Status", "Created At"], activityRows.length > 0 ? activityRows : [["", "No recent activity.", "", "", ""]]);
  });
}

function buildParcelRecordsPdf({ metadata, records }) {
  return buildPdfBuffer((doc) => {
    addPdfHeader(doc, metadata);
    addPdfSectionTitle(doc, "Parcel Records");
    addPdfRows(doc, ["Tracking", "Unit", "Courier", "Status", "Registered At"], records.map((record) => [
      record.tracking_number,
      record.unit_full_code,
      record.courier_name,
      record.display_status,
      record.created_at
    ]));

    if (records.length === 0) {
      doc.fontSize(9).fillColor("#4f5b67").text("No parcel records found for this period.");
    }
  });
}

function buildUserAccountSummaryPdf({ metadata, summary }) {
  return buildPdfBuffer((doc) => {
    addPdfHeader(doc, metadata);
    addPdfSectionTitle(doc, "Role And Status Summary");
    addPdfRows(doc, ["Role", "Status", "Total Count"], summary.roleStatusSummary.map((item) => [
      item.role,
      item.status,
      item.total_count
    ]));

    addPdfSectionTitle(doc, "Account Creation Trend");
    addPdfRows(doc, ["Month", "New Accounts"], summary.accountCreationTrend.map((item) => [
      item.account_creation_month,
      item.new_account_count
    ]));
  });
}

function buildReportFilename({ reportType, format, period, startDate }) {
  const datePart = startDate || new Date().toISOString().slice(0, 10);
  return `parcel-nexus-${reportSlug(reportType)}-${period}-${datePart}.${format}`;
}

async function buildReportContent({ reportType, format, config, metadata, requester }) {
  if (reportType === "dashboard_summary") {
    const dashboard = await getAdminDashboard({
      requester,
      period: config.period,
      startDate: metadata.requestedStartDate
    });

    if (dashboard.error) {
      return dashboard;
    }

    return {
      content: format === "csv"
        ? buildDashboardSummaryCsv({ metadata, dashboard })
        : await buildDashboardSummaryPdf({ metadata, dashboard })
    };
  }

  if (reportType === "parcel_records") {
    const records = await getParcelRecordsForReport(config);

    return {
      content: format === "csv"
        ? buildParcelRecordsCsv({ metadata, records })
        : await buildParcelRecordsPdf({ metadata, records })
    };
  }

  const summary = await getUserAccountSummaryForReport(config);

  return {
    content: format === "csv"
      ? buildUserAccountSummaryCsv({ metadata, summary })
      : await buildUserAccountSummaryPdf({ metadata, summary })
  };
}

export async function getAdminDashboard({ requester, period = "day", startDate }) {
  if (requester.role !== "ADMIN") {
    return { error: "FORBIDDEN" };
  }

  const normalizedPeriod = String(period || "day").trim().toLowerCase();

  if (!VALID_PERIODS.includes(normalizedPeriod)) {
    return { error: "INVALID_PERIOD" };
  }

  const config = getPeriodConfig(normalizedPeriod, { startDate });

  if (config.error) {
    return { error: config.error };
  }
  const [totalParcels, previousTotalParcels, collected, previousCollected, pendingData] = await Promise.all([
    getRangeParcelCount(config),
    getRangeParcelCount({
      start: config.previousStart,
      end: config.previousEnd
    }),
    getRangeCollectedCount(config),
    getRangeCollectedCount({
      start: config.previousStart,
      end: config.previousEnd
    }),
    getCurrentPendingAndOverdue()
  ]);
  const [disputeData, parcelTrend, statusDistribution, systemSummary, recentActivity] = await Promise.all([
    getDisputeKpi({
      start: config.start,
      end: config.end,
      previousStart: config.previousStart,
      previousEnd: config.previousEnd,
      comparisonLabel: config.comparisonLabel
    }),
    getParcelTrend(config),
    getStatusDistribution(),
    getSystemSummary(),
    getRecentActivity()
  ]);

  return {
    period: config.period,
    range: {
      label: config.label,
      start: toIso(config.start),
      end: toIso(config.end)
    },
    comparison_range: {
      start: toIso(config.previousStart),
      end: toIso(config.previousEnd)
    },
    kpis: {
      total_parcels: {
        label: "Parcels Logged",
        value: totalParcels,
        comparison_label: config.comparisonLabel,
        comparison_value: previousTotalParcels,
        change_percent: calculateChangePercent(totalParcels, previousTotalParcels)
      },
      pending_collection: {
        label: "Pending Collection",
        value: pendingData.pendingCollection,
        overdue_count: pendingData.overdueCount,
        comparison_label: config.comparisonLabel,
        comparison_value: null,
        change_percent: null,
        message: "Pending collection is a current operational count, not a historical snapshot."
      },
      collected: {
        label: "Collected Parcels",
        value: collected,
        comparison_label: config.comparisonLabel,
        comparison_value: previousCollected,
        change_percent: calculateChangePercent(collected, previousCollected)
      },
      open_disputes: disputeData.kpi
    },
    alert:
      pendingData.overdueCount > 0
        ? {
            type: "overdue",
            overdue_count: pendingData.overdueCount,
            message:
              pendingData.overdueCount === 1
                ? "1 parcel is overdue."
                : `${pendingData.overdueCount} parcels are overdue.`
          }
        : {
            type: "none",
            overdue_count: 0,
            message: ""
          },
    parcel_trend: parcelTrend,
    status_distribution: statusDistribution,
    dispute_summary: disputeData.summary,
    system_summary: systemSummary,
    recent_activity: recentActivity
  };
}

export async function getGuardDashboard({ requester, period = "today", startDate }) {
  if (requester.role !== "GUARD") {
    return { error: "GUARD_FORBIDDEN" };
  }

  const normalizedPeriod = String(period || "today").trim().toLowerCase();
  const config = getGuardPeriodConfig(normalizedPeriod, { startDate });

  if (config.error) {
    return { error: config.error };
  }

  const [summary, latestLoggedParcels, pendingCollectionParcels] = await Promise.all([
    getGuardSummary(config),
    getLatestLoggedParcelsForGuard(),
    getPendingCollectionParcelsForGuard()
  ]);
  const overdueCount = numberValue(summary.overdue_parcels);

  return {
    guard: {
      name: displayUserName(requester),
      email: requester.email
    },
    period: {
      selected: config.selected,
      start: toIso(config.start),
      end: toIso(config.end),
      label: config.label
    },
    summary,
    alert:
      overdueCount > 0
        ? {
            type: "overdue",
            count: overdueCount,
            message: overdueCount === 1 ? "1 parcel is overdue." : `${overdueCount} parcels are overdue.`
          }
        : {
            type: "none",
            count: 0,
            message: ""
          },
    latest_logged_parcels: latestLoggedParcels,
    pending_collection_parcels: pendingCollectionParcels,
    dispute_summary: {
      available: false,
      message: "Dispute module is not implemented yet."
    }
  };
}

export async function generateAdminReport({
  requester,
  reportType,
  format,
  period = "day",
  startDate
}) {
  if (requester.role !== "ADMIN") {
    return { error: "FORBIDDEN" };
  }

  const normalizedReportType = String(reportType || "").trim().toLowerCase();
  const normalizedFormat = String(format || "").trim().toLowerCase();
  const normalizedPeriod = String(period || "day").trim().toLowerCase();

  if (!VALID_REPORT_TYPES.includes(normalizedReportType)) {
    return { error: "INVALID_REPORT_TYPE" };
  }

  if (!VALID_REPORT_FORMATS.includes(normalizedFormat)) {
    return { error: "INVALID_FORMAT" };
  }

  if (!VALID_PERIODS.includes(normalizedPeriod)) {
    return { error: "INVALID_PERIOD" };
  }

  const config = getPeriodConfig(normalizedPeriod, { startDate });

  if (config.error) {
    return { error: config.error };
  }

  const metadata = createMetadata({
    reportType: normalizedReportType,
    format: normalizedFormat,
    config,
    requester,
    startDate
  });
  const reportContent = await buildReportContent({
    reportType: normalizedReportType,
    format: normalizedFormat,
    config,
    metadata,
    requester
  });

  if (reportContent.error) {
    return reportContent;
  }

  return {
    filename: buildReportFilename({
      reportType: normalizedReportType,
      format: normalizedFormat,
      period: normalizedPeriod,
      startDate
    }),
    contentType:
      normalizedFormat === "csv"
        ? "text/csv; charset=utf-8"
        : "application/pdf",
    content: reportContent.content
  };
}
